# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpipboy < Formula
  desc "Context-aware Terraform CLI tool with real-time status display"
  homepage "https://github.com/StanleyXie/tfpipboy"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.1/tfpipboy_Darwin_x86_64.tar.gz"
      sha256 "0dbc9d6c2470571a56d9dc70e960c26bff03cbf3b330e9dd1f856462563601a3"

      def install
        bin.install "tfpipboy"
      end
    end
    on_arm do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.1/tfpipboy_Darwin_arm64.tar.gz"
      sha256 "b559476b89b28b9dd6b4b4c2a9b26044f7261b86c27364b59eea252b662ed2c4"

      def install
        bin.install "tfpipboy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.1/tfpipboy_Linux_x86_64.tar.gz"
        sha256 "e54a80c49cfe8d22abe6895406c617aaf67c805e6d03905116823de176292768"

        def install
          bin.install "tfpipboy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.1/tfpipboy_Linux_arm64.tar.gz"
        sha256 "04be077fbb910c5231f184aac88a68a20c8138994d635cb84946c720f36a2f28"

        def install
          bin.install "tfpipboy"
        end
      end
    end
  end

  test do
    system "#{bin}/tfpipboy", "--version"
  end
end
