# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpipboy < Formula
  desc "Context-aware Terraform CLI tool with real-time status display"
  homepage "https://github.com/StanleyXie/tfpipboy"
  version "0.6.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Darwin_x86_64.tar.gz"
      sha256 "156ef30265888eec829389c07b9800882ddde1b373c73ce7af6b8acf5d5a89d9"

      def install
        bin.install "tfpipboy"
      end
    end
    on_arm do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Darwin_arm64.tar.gz"
      sha256 "fcd892195b6d97e9da572c52cb4f0f54477976fd032a3c944d5460dd039ed252"

      def install
        bin.install "tfpipboy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Linux_x86_64.tar.gz"
        sha256 "b8be2284d1e3b5aa416d1aec97f5049bc35619014162b419cf9c076114b89ca2"

        def install
          bin.install "tfpipboy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Linux_arm64.tar.gz"
        sha256 "11b9bfb6085d3de83ba013f84509042fed8a825f0d254b7a39b33cf774133ebd"

        def install
          bin.install "tfpipboy"
        end
      end
    end
  end

  test do
    system "#{bin}/tfpipboy", "--version"
  end
end
