# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpipboy < Formula
  desc "Context-aware Terraform CLI tool with real-time status display"
  homepage "https://github.com/StanleyXie/tfpipboy"
  version "0.7.0-beta.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.7.0-beta.1/tfpipboy_Darwin_x86_64.tar.gz"
      sha256 "03a1d8ed5f617667e8fcf71eec92950253ddc064efe966b235ed1b975523a6c7"

      def install
        bin.install "tfpipboy"
      end
    end
    on_arm do
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.7.0-beta.1/tfpipboy_Darwin_arm64.tar.gz"
      sha256 "914c4eb8b7d9ca1df4ed7dd046963f1769169d97543bc6c57351e62087b9e7ad"

      def install
        bin.install "tfpipboy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.7.0-beta.1/tfpipboy_Linux_x86_64.tar.gz"
        sha256 "05e24e33eaa15adddb6c7518e15b183016cf159aae25a95b98f2256038402710"

        def install
          bin.install "tfpipboy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.7.0-beta.1/tfpipboy_Linux_arm64.tar.gz"
        sha256 "3c856b2b899c9ef5c3f57caaf6d028797211a40ad6b280d64d4db97b1f71e50b"

        def install
          bin.install "tfpipboy"
        end
      end
    end
  end

  test do
    system "#{bin}/tfpipboy", "--version"
  end
end
