# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpipboy < Formula
  desc "Context-aware Terraform CLI tool with real-time status display"
  homepage "https://github.com/StanleyXie/tfpipboy"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Darwin_x86_64.tar.gz"
      sha256 "eb3ad36a0c0600357d243a2a891dfb3d31030b4dc5cda22a45d36ff99fee8d04"

      def install
        bin.install "tfpipboy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Darwin_arm64.tar.gz"
      sha256 "8ea7b1fa4cf0a871c01006d0931682eda3f5a552e7e6c43096ddec0942adf001"

      def install
        bin.install "tfpipboy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Linux_x86_64.tar.gz"
      sha256 "6e2da8ef3c59f2ffc6d3cbf8736382110322e4da2612d67bfb04d4c11bc6b04f"
      def install
        bin.install "tfpipboy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.3/tfpipboy_Linux_arm64.tar.gz"
      sha256 "b44964a4a403638bdc09b15ad1a6651551420ba841910de4c1ab7e1b121a1e96"
      def install
        bin.install "tfpipboy"
      end
    end
  end

  test do
    system "#{bin}/tfpipboy", "--version"
  end
end
