# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpipboy < Formula
  desc "Context-aware Terraform CLI tool with real-time status display"
  homepage "https://github.com/StanleyXie/tfpipboy"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.4/tfpipboy_Darwin_x86_64.tar.gz"
      sha256 "095ecf3f5e1f3bae2db41a348a3d40b6aa37e56874db2d2263bcd04685bdf787"

      def install
        bin.install "tfpipboy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.4/tfpipboy_Darwin_arm64.tar.gz"
      sha256 "6b8ca7d6d56fec3a3b840c484e272358769edb064edcf40193bd0a046d3635aa"

      def install
        bin.install "tfpipboy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.4/tfpipboy_Linux_x86_64.tar.gz"
      sha256 "fc1750b4a7c735d775097dc1a6035183c8423b7e22feee55ab95b443041d1862"
      def install
        bin.install "tfpipboy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanleyXie/tfpipboy/releases/download/v0.6.4/tfpipboy_Linux_arm64.tar.gz"
      sha256 "b907c2bfd1a555e65b0fbfc7194b2070b4709071f3ad5a32638b0e87a94a8908"
      def install
        bin.install "tfpipboy"
      end
    end
  end

  test do
    system "#{bin}/tfpipboy", "--version"
  end
end
